/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bcd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class App {

    public static void main(String[] args) {
        
        String dbUri = "jdbc:mysql://ampto.sj.ifsc.edu.br:33006/lab01emerson?user=emerson&password=bcd1234";

        //String dbMysql = "jdbc:mysql://ampto.sj.i";

        String query = "SELECT * FROM Pessoa";

        try (
                Connection conexao = DriverManager.getConnection(dbUri);
                PreparedStatement statement = conexao.prepareStatement(query);
                ResultSet resultSet = statement.executeQuery();

            ) {
               
                while(resultSet.next()){
                    System.out.println("ID:" + resultSet.getInt("idPessoa"));
                }


        }catch (Exception e){
            e.printStackTrace();
        }
    }
}
